services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - aimo-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    container_name: frontend
    ports:
      - "5173:80" # frontend served via nginx on port 80
    depends_on:
      - backend
    networks:
      - aimo-net
  # nginx:
  #   image: nginx:1.20.1
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 8080:80
  #   container_name: reverse-proxy
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - aimo-net

networks:
  aimo-net:
    driver: bridge


  # nginx:
  #   image: nginx:1.20.1
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - frontend
  #     - backend
  #   container_name: reverse-proxy-blog
# Optional: e2e tests
#   e2e:
#     build:
#       context: ./e2e
#     depends_on:
#       - backend
#       - frontend
#     networks:
#       - aimo-net

 
